{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokedByDevice","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason\/revokedbydevice"]}],"metadata":{"symbolKind":"case","role":"symbol","title":"ReaderConnectionFailureReason.revokedByDevice","roleHeading":"Case","modules":[{"name":"MobilePaymentsSDK"}],"externalID":"c:@M@MobilePaymentsSDKAPI@E@SQMPReaderConnectionFailureReason@SQMPReaderConnectionFailureReasonRevokedByDevice","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"revokedByDevice"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI","doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason\/revokedByDevice"},"abstract":[{"type":"text","text":"An error with the device occurred while attempting to establish a connection to Square."}],"references":{"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI/ReaderConnectionFailureReason":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReaderConnectionFailureReason","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason","kind":"symbol","abstract":[{"text":"Indicates why a reader might have failed to connect to Square.","type":"text"}],"identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason","title":"ReaderConnectionFailureReason","navigatorTitle":[{"kind":"identifier","text":"ReaderConnectionFailureReason"}],"type":"topic"},"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI":{"role":"collection","type":"topic","url":"\/documentation\/mobilepaymentssdkapi","title":"MobilePaymentsSDK","abstract":[],"identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI","kind":"symbol"},"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI/ReaderConnectionFailureReason/revokedByDevice":{"role":"symbol","identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason\/revokedByDevice","type":"topic","title":"ReaderConnectionFailureReason.revokedByDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"revokedByDevice","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason\/revokedbydevice","abstract":[{"type":"text","text":"An error with the device occurred while attempting to establish a connection to Square."}]}}}