{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason\/revokedbydevice"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokedByDevice"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@MobilePaymentsSDKAPI@E@SQMPReaderConnectionFailureReason@SQMPReaderConnectionFailureReasonRevokedByDevice","roleHeading":"Case","title":"ReaderConnectionFailureReason.revokedByDevice","modules":[{"name":"MobilePaymentsSDKAPI"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI","doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason\/revokedByDevice","interfaceLanguage":"swift"},"abstract":[{"text":"An error with the device occurred while attempting to establish a connection to Square.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokedByDevice"}]}]}],"references":{"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI":{"abstract":[],"kind":"symbol","url":"\/documentation\/mobilepaymentssdkapi","title":"MobilePaymentsSDKAPI","role":"collection","identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI","type":"topic"},"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI/ReaderConnectionFailureReason/revokedByDevice":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"revokedByDevice","kind":"identifier"}],"abstract":[{"text":"An error with the device occurred while attempting to establish a connection to Square.","type":"text"}],"identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason\/revokedByDevice","url":"\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason\/revokedbydevice","title":"ReaderConnectionFailureReason.revokedByDevice"},"doc://com.squareup.MobilePaymentsSDKAPI/documentation/MobilePaymentsSDKAPI/ReaderConnectionFailureReason":{"navigatorTitle":[{"text":"ReaderConnectionFailureReason","kind":"identifier"}],"identifier":"doc:\/\/com.squareup.MobilePaymentsSDKAPI\/documentation\/MobilePaymentsSDKAPI\/ReaderConnectionFailureReason","title":"ReaderConnectionFailureReason","url":"\/documentation\/mobilepaymentssdkapi\/readerconnectionfailurereason","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Indicates why a reader might have failed to connect to Square.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReaderConnectionFailureReason","kind":"identifier"}]}}}